# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.encode_geno <- function(g, old_values, new_values) {
    .Call('qtl2convert_encode_geno', PACKAGE = 'qtl2convert', g, old_values, new_values)
}

.consensus_geno <- function(g) {
    .Call('qtl2convert_consensus_geno', PACKAGE = 'qtl2convert', g)
}

.find_consensus_geno <- function(g) {
    .Call('qtl2convert_find_consensus_geno', PACKAGE = 'qtl2convert', g)
}

